#!/bin/bash
#SBATCH --job-name="lcdb-test-data"
#SBATCH --partition="norm"
#SBATCH --time=24:00:00

# make logdir
if [[ ! -e logs ]]; then mkdir -p logs; fi

SNAKEFILE=Snakefile
#echo $SNAKEFILE

# Run snakemake
#(source activate lcdb-test-data; \
(
    time snakemake \
    -p \
    -s $SNAKEFILE \
    -k \
    --rerun-incomplete \
    --jobname "s.{rulename}.{jobid}.sh" \
    -j 999 \
    --cluster-config config/clusterconfig.yaml \
    --verbose \
    --cluster 'sbatch {cluster.prefix} --cpus-per-task={threads} --output=logs/{rule}.o.%j --error=logs/{rule}.e.%j' \
    --use-conda \
    --latency-wait=60 \
    ${@:2} \
    ) > "${SNAKEFILE}.log" 2>&1

SNAKE_PID=$!

finish(){
    echo 'Stopping running snakemake job.'
    kill -SIGINT $SNAKE_PID
    exit 0
}
trap finish SIGTERM

wait $SNAKE_PID
